### ISSUE TITLE
I have a question for you about Unittests Project

### ISSUE THREAD

**Issue by thonghn2** [develbranch/TinyAntivirus#1]
I see you used Google Test in Unittest Project, could you tell me gtest.lib, gtestd.lib version number? I'm try use https://github.com/google/googletest but it not work.
![image](https://cloud.githubusercontent.com/assets/17896482/17761736/ed0407ae-6533-11e6-933b-6dab90f5f7d3.png)

**Comment by quangnh89** [comment]
Thank you. I have [updated](https://github.com/develbranch/TinyAntivirus/commit/bb70320af41d4390997606a29f6d8fdae0a1deed) runtime-library configuration of all project files to compile with /MTd instead of /MDd. I think the problem has been solved. Please confirm me after re-building it.

**Comment by quangnh89** [comment]
You can open Windows Command Prompt (cmd.exe) and run:

``` batch
git clone --recursive https://github.com/develbranch/TinyAntivirus.git
cd TinyAntivirus
ci\windows\build_appveyor.bat x86 Debug
```

Everything will be cloned and built automatically.

**Comment by thonghn2** [comment]
Thank for your reply.

**Comment by quangnh89** [comment]
may we close this issue?
